### ISSUE TITLE
Get by ASN returns empty "poc_set": []

### ISSUE THREAD

**Issue by cameronff** [peeringdb/1to2#53]
for example: 

https://beta.peeringdb.com/api/asn/16509

"poc_set": [],
"created": "2007-12-20T16:39:54Z",
"updated": "2015-10-20T23:07:59Z",
"status": "0"

While there are contacts listed for net_id=1418

ie. https://beta.peeringdb.com/api/poc?id=2010

**Comment by vegu** [comment]
cannot reproduce this - i get a populated poc_set on both endpoints:

https://beta.peeringdb.com/api/asn/16509
https://beta.peeringdb.com/api/net/1418

Can you confirm that you were authenticated - poc data is only available with authenticated sessions - there is currently a bug where authentication isnt properly checked on /api/poc list retrieval (#55)

**Comment by slow2k** [comment]
I can confirm this issue. I also can't see a populated poc_set at:
https://beta.peeringdb.com/api/asn/16509 

or any other records. It doesn't matter if I do this with authentification or not.

**Comment by vegu** [comment]
Curious, thanks for confirming. How are you authenticating ? HTTP Basic auth ?

**Comment by slow2k** [comment]
I did a HTTP auth ie:
https://guest:guest@beta.peeringdb.com/api/asn/16509
I also tried this with normal user credentials.
A Curl request results in same.

**Comment by vegu** [comment]
Thanks,  HTTP auth via url parameters is currently not functional.

Right now you have to set the Authentication headers in the request

For curl this works for me

curl --user <user>:<password> https://beta.peeringdb.com/api/asn/16509

In order to get your browser to authenticate, go to https://beta.peeringdb.com/login and auth there then use the api with that session.

Also just to clarify, guest authentication will not receive any poc data at this point.

Cheers

**Comment by vegu** [comment]
Removed older post, in order avoid confusion as it contained faulty test results on my part.

Using curl these work for me by returning a populated poc_set

curl http://user:password@beta.peeringdb.com/api/asn/16509
curl --user user:password http://beta.peeringdb.com/api/asn/16509

guest:guest is no longer a thing as that account has been removed which is a change that needs to be reflected in the documentation still

so since you're getting an empty poc_set even when using your real credentials, im thinking it might a permissioning issue

**Comment by cameronff** [comment]
thanks for getting back to this one. it appears my account isn't verified - "cameronf" registered with my work email address

Should I make a separate account for automated queries against the API? 

thanks for looking into this one, i'm cameron-16509 on #ix if you'd like to talk there feel free to hit me up.

**Comment by vegu** [comment]
Was a permissions issue
